title: Kalyan Dechiraju
author: kalyandechiraju
email: kalyandechiraju@outlook.com
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to my blog. I am Senior Android Developer @Playo.
  Trying to teach machines to think.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Kalyan Dechiraju
  tagline: Android Developer
  date_format: "%b %-d, %Y"
  style: purple
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: kalyandechiraju
    github: kalyandechiraju
    linkedIn: in/kalyandechiraju
    rss: rss

header_pages:
  - about.md

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
