# Site
name: "Kalyan Dechiraju"
title: "Kalyan Dechiraju"
description: "Android Developer"
# logo: ""
# favicon: ""
baseurl:
# google_analytics: ""
disqus: "https-kalyandechiraju-github-io"
# mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kalyan:
    name: Kalyan Dechiraju
    display_name: Kalyan
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: kalyandechiraju@outlook.com
    web: https://kalyandechiraju.github.io
    twitter: https://twitter.com/kalyandechiraju
    description: "Adroid Developer. Trying to teach machines to learn."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
